# Generated by Django 4.2.4 on 2023-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225, null=True)),
                ('lastname', models.CharField(max_length=225, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=125, null=True)),
                ('uid', models.CharField(max_length=225, null=True)),
                ('admission', models.CharField(max_length=225, null=True)),
                ('department', models.CharField(max_length=255)),
                ('nof', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='static/images/icon.png', null=True, upload_to='image/')),
            ],
        ),
    ]
